import news1 from '../assets/news1.png'
import news2 from '../assets/news2.png'
import news3 from '../assets/news3.png'

import lost1 from '../assets/lost1.jpg'
import lost2 from '../assets/lost2.jpg'
import lost3 from '../assets/lost3.jpg'
import lost4 from '../assets/lost4.jpg'

export const announcementData = [
    { id: 1, title: "Dog in Ukraine", reportedBy:'Edrie Isaac Cruz', date: '2022-04-21', img:news1, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed placerat eleifend ipsum a porttitor. Praesent tempus, urna quis luctus varius, lorem urna mollis mi, id suscipit dolor odio a ligula. Suspendisse ut luctus sem. Nullam sit amet volutpat lectus. Maecenas non enim in tellus luctus ultrices pellentesque in orci. Sed ac sagittis eros, ut faucibus velit. Vivamus ullamcorper arcu in augue maximus, sed imperdiet leo scelerisque. Nulla quis ultrices nisl, ac mattis risus. Aliquam facilisis tortor non leo vehicula maximus. Quisque quis nisl ex..'},
    { id: 2, title: "Upcoming Vaccination", reportedBy:'Edrie Isaac Cruz', date: '2022-03-09', img:news2, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed placerat eleifend ipsum a porttitor. Praesent tempus, urna quis luctus varius, lorem urna mollis mi, id suscipit dolor odio a ligula. Suspendisse ut luctus sem. Nullam sit amet volutpat lectus. Maecenas non enim in tellus luctus ultrices pellentesque in orci. Sed ac sagittis eros, ut faucibus velit. Vivamus ullamcorper arcu in augue maximus, sed imperdiet leo scelerisque. Nulla quis ultrices nisl, ac mattis risus. Aliquam facilisis tortor non leo vehicula maximus. Quisque quis nisl ex..'},
    { id: 3, title: "Pet Gadgets",reportedBy:'Edrie Isaac Cruz',  date: '2022-02-01', img:news3, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed placerat eleifend ipsum a porttitor. Praesent tempus, urna quis luctus varius, lorem urna mollis mi, id suscipit dolor odio a ligula. Suspendisse ut luctus sem. Nullam sit amet volutpat lectus. Maecenas non enim in tellus luctus ultrices pellentesque in orci. Sed ac sagittis eros, ut faucibus velit. Vivamus ullamcorper arcu in augue maximus, sed imperdiet leo scelerisque. Nulla quis ultrices nisl, ac mattis risus. Aliquam facilisis tortor non leo vehicula maximus. Quisque quis nisl ex..'},
    { id: 4, title: "Dog", reportedBy:'Edrie Isaac Cruz', date: '2022-01-12', img:news1, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed placerat eleifend ipsum a porttitor. Praesent tempus, urna quis luctus varius, lorem urna mollis mi, id suscipit dolor odio a ligula. Suspendisse ut luctus sem. Nullam sit amet volutpat lectus. Maecenas non enim in tellus luctus ultrices pellentesque in orci. Sed ac sagittis eros, ut faucibus velit. Vivamus ullamcorper arcu in augue maximus, sed imperdiet leo scelerisque. Nulla quis ultrices nisl, ac mattis risus. Aliquam facilisis tortor non leo vehicula maximus. Quisque quis nisl ex..'},
    { id: 5, title: "Dog", reportedBy:'Edrie Isaac Cruz', date: '2022-01-12', img:news1, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed placerat eleifend ipsum a porttitor. Praesent tempus, urna quis luctus varius, lorem urna mollis mi, id suscipit dolor odio a ligula. Suspendisse ut luctus sem. Nullam sit amet volutpat lectus. Maecenas non enim in tellus luctus ultrices pellentesque in orci. Sed ac sagittis eros, ut faucibus velit. Vivamus ullamcorper arcu in augue maximus, sed imperdiet leo scelerisque. Nulla quis ultrices nisl, ac mattis risus. Aliquam facilisis tortor non leo vehicula maximus. Quisque quis nisl ex..'},
  ];

export const lostfoundData = [
    { id: 1, owner: 'Edrie Cruz', status:'lost', email: 'edriecruz@gmail.com', address:'Marikina City', gender: 'Male', lastSeen: 'Antipolo' ,name: "Blacky", lost: '2022-04-21', img:lost1, contact:'09123456789', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.'},
    { id: 2, owner: 'N/A', status:'lost', email: 'juswa@gmail.com', address:'Marikina City', gender: 'Male', lastSeen: 'Antipolo' ,name: "Bullsbal", lost: '2022-03-09', img:lost2, contact:'09123456789', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.'},
    { id: 3, owner: 'Cad Mateo', status:'lost', email: 'cad@gmail.com', address:'Mandaluyong City', gender: 'Male', lastSeen: 'Antipolo' ,name: "Brownie", lost: '2022-02-01', img:lost3, contact:'09123456789', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.'},
    { id: 4, owner: 'Enrico Ramos', status:'found', email: 'enwicowamos@gmail.com', address:'Quezon City', gender: 'Male', lastSeen: 'Antipolo' ,name: "Bullydog", lost: '2022-01-12', img:lost4, contact:'09123456789', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.'},
    { id: 5, owner: 'N/A', status:'found', email: 'congressman@gmail.com', address:'Cainta, Rizal', gender: 'Male', lastSeen: 'Antipolo' ,name: "Chuck", lost: '2022-01-12', img:lost4, contact:'09123456789', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.'},
  ];